# -*- coding: utf-8 -*-
"""Algo Materi 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i8sYuIBqH7Sy3DYKz64bIkL2vnfPKuxp
"""

nama = input("Nama: ")

masuk = float(input("Jam masuk kerja: "))

print("Selamat pagi", nama)

keluar = float(input("Jam keluar kerja: "))

jam_kerja = keluar - masuk

print("Selamat Sore", nama)

print("-----rincian gaji-----")

print("Nama:", nama)

# jumlah jam kerja
print(f"Waktu kerja: {jam_kerja} jam")

print("Gaji perhari:Rp 175000 ")

# Gaji per hari
gaji_per_hari = 175000  # Gaji per hari sebesar 175 ribu

# Menghitung gaji tambahan jika jam kerja lebih dari 8 jam
if jam_kerja > 8:
    jam_lebih = jam_kerja - 8
    gaji_tambahan = jam_lebih * 15000  # 15 ribu per jam
else:
    gaji_tambahan = 0

# Menghitung total gaji per hari
total_gaji = gaji_per_hari + gaji_tambahan

# Menampilkan hasil
print(f"Lembur: {total_gaji} ribu rupiah")