# -*- coding: utf-8 -*-
"""tugas algo materi 12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yml9Gt2w4KcMiYq56I2AVkKa8q63xFqL
"""

def hitung_rata_rata(nilai):
    jumlah_nilai = sum(nilai)
    rata_rata = jumlah_nilai / len(nilai)
    return rata_rata

def main():
    # Input jumlah mahasiswa
    jumlah_mahasiswa = int(input("Masukkan jumlah mahasiswa: "))

    # Inisialisasi list untuk menyimpan nama dan nilai mahasiswa
    nama_mahasiswa = []
    nilai_mahasiswa = []

    # Input nama dan nilai mahasiswa
    for i in range(jumlah_mahasiswa):
        nama = input(f"Masukkan nama mahasiswa ke-{i + 1}: ")
        nilai = float(input(f"Masukkan nilai praktikum {nama}: "))

        nama_mahasiswa.append(nama)
        nilai_mahasiswa.append(nilai)

    # Hitung rata-rata nilai
    rata_rata = hitung_rata_rata(nilai_mahasiswa)

    # Tampilkan hasil
    print("\n=== Hasil ===")
    for i in range(jumlah_mahasiswa):
        print(f"{nama_mahasiswa[i]}: {nilai_mahasiswa[i]}")

    print(f"\nRata-rata nilai praktikum: {rata_rata}")

if __name__ == "__main__":
    main()