# -*- coding: utf-8 -*-
"""tugas akhir algo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yml9Gt2w4KcMiYq56I2AVkKa8q63xFqL
"""

def hitung_rata_rata_praktikum(nilai_mahasiswa):
    rata_rata_praktikum_per_baris = [sum(nilai) / len(nilai) for nilai in nilai_mahasiswa]
    return rata_rata_praktikum_per_baris

def main():
    # Input jumlah mahasiswa
    jumlah_mahasiswa = int(input("Masukkan jumlah mahasiswa: "))

    # Inisialisasi list untuk menyimpan nama dan nilai mahasiswa
    nama_mahasiswa = []
    nilai_mahasiswa = []

    # Input nama dan nilai mahasiswa
    for i in range(jumlah_mahasiswa):
        nama = input(f"Masukkan nama mahasiswa ke-{i + 1}: ")
        jumlah_praktikum = int(input(f"Masukkan jumlah praktikum untuk {nama}: "))

        # Inisialisasi list untuk menyimpan nilai praktikum setiap mahasiswa
        nilai_praktikum = []

        # Input nilai praktikum
        for j in range(jumlah_praktikum):
            nilai = float(input(f"Masukkan nilai praktikum ke-{j + 1} untuk {nama}: "))
            nilai_praktikum.append(nilai)

        # Tambahkan nilai praktikum ke dalam list nilai_mahasiswa
        nilai_mahasiswa.append(nilai_praktikum)
        nama_mahasiswa.append(nama)

    # Hitung rata-rata per baris
    rata_rata_baris = hitung_rata_rata_praktikum(nilai_mahasiswa)

    # Tampilkan hasil
    header_kolom_praktikum = ["Praktikum {}".format(i + 1) for i in range(len(nilai_mahasiswa[0]))]
    header_format = "{:<15} {:<15} " + " ".join("{:<15}" for _ in header_kolom_praktikum)

    print(header_format.format("Nama Mahasiswa", "Rata-rata", *header_kolom_praktikum))

    for i in range(jumlah_mahasiswa):
        print("{:<15} {:<15} ".format(nama_mahasiswa[i], round(rata_rata_baris[i], 2)), end="")

        # Tampilkan nilai praktikum per mahasiswa
        for nilai in nilai_mahasiswa[i]:
            print("{:<15}".format(nilai), end="")
        print()

    # Tampilkan rata-rata praktikum
    print("\nRata-rata Praktikum: ", end="")
    for rata in rata_rata_baris:
        print("{:<15}".format(round(rata, 2)), end="")

if __name__ == "__main__":
    main()

def hitung_rata_rata_praktikum(nilai_mahasiswa):
    rata_rata_praktikum_per_baris = {i + 1: sum(nilai) / len(nilai) for i, nilai in enumerate(nilai_mahasiswa)}
    return rata_rata_praktikum_per_baris

def main():
    # Input jumlah mahasiswa
    jumlah_mahasiswa = int(input("Masukkan jumlah mahasiswa: "))

    # Inisialisasi dictionary untuk menyimpan data mahasiswa
    data_mahasiswa = {}

    # Input data mahasiswa
    for i in range(jumlah_mahasiswa):
        nama = input(f"Masukkan nama mahasiswa ke-{i + 1}: ")
        jumlah_praktikum = int(input(f"Masukkan jumlah praktikum untuk {nama}: "))

        # Inisialisasi dictionary untuk menyimpan data praktikum setiap mahasiswa
        nilai_praktikum = {"Nilai Praktikum": []}

        # Input nilai praktikum
        for j in range(jumlah_praktikum):
            nilai = float(input(f"Masukkan nilai praktikum ke-{j + 1} untuk {nama}: "))
            nilai_praktikum["Nilai Praktikum"].append(nilai)

        # Tambahkan data mahasiswa ke dalam dictionary data_mahasiswa
        data_mahasiswa[nama] = nilai_praktikum

    # Hitung rata-rata per baris
    rata_rata_baris = hitung_rata_rata_praktikum([mahasiswa["Nilai Praktikum"] for mahasiswa in data_mahasiswa.values()])

    # Tampilkan hasil
    header_kolom_praktikum = ["Praktikum {}".format(i + 1) for i in range(len(list(data_mahasiswa.values())[0]["Nilai Praktikum"]))]
    header_format = "{:<15} {:<15} " + " ".join("{:<15}" for _ in header_kolom_praktikum)

    print(header_format.format("Nama Mahasiswa", "Rata-rata", *header_kolom_praktikum))

    for nama, mahasiswa in data_mahasiswa.items():
        print("{:<15} {:<15} ".format(nama, round(rata_rata_baris[list(data_mahasiswa.keys()).index(nama) + 1], 2)), end="")

        # Tampilkan nilai praktikum per mahasiswa
        for nilai in mahasiswa["Nilai Praktikum"]:
            print("{:<15}".format(nilai), end="")
        print()

    # Tampilkan rata-rata praktikum
    print("\nRata-rata Praktikum: ", end="")
    for rata in rata_rata_baris.values():
        print("{:<15}".format(round(rata, 2)), end="")

if __name__ == "__main__":
    main()