# -*- coding: utf-8 -*-
"""Tugas Algo Materi 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PWQGNAME1wJL13KRN0hlxJXJm2bshzRz
"""

def main():
    nama, masuk, keluar = MasukkanData()
    jam_kerja = keluar - masuk
    gaji_pokok, gaji_tambahan, total_gaji = HitungGaji(jam_kerja)
    TampilkanRincian(nama, jam_kerja, gaji_pokok, gaji_tambahan, total_gaji)

def MasukkanData():
    nama = input("Nama: ")
    masuk = float(input("Jam masuk kerja: "))
    keluar = float(input("Jam keluar kerja: "))
    return nama, masuk, keluar

def HitungGaji(jam_kerja):
    gaji_pokok = 175000
    gaji_tambahan = 0

    if jam_kerja > 8:
        jam_lebih = jam_kerja - 8
        gaji_tambahan = jam_lebih * 15000

    total_gaji = gaji_pokok + gaji_tambahan
    return gaji_pokok, gaji_tambahan, total_gaji

def TampilkanRincian(nama, jam_kerja, gaji_pokok, gaji_tambahan, total_gaji):
    print("Selamat Sore", nama)
    print("-----Rincian Gaji-----")
    print("Nama:", nama)
    print(f"Waktu kerja: {jam_kerja} jam")
    print(f"Gaji pokok: Rp", gaji_pokok)
    print(f"Lembur: Rp", total_gaji)

# Memanggil fungsi utama
if __name__ == "__main__":
    main()

def main():
    masuk = BacaInputJam()
    keluar = BacaInputJam()
    nama = sapa()
    gaji_pokok, gaji_tambahan, total_gaji = HitungLembur(jam_kerja)
    TampilkanRincian(nama, jam_kerja, gaji_pokok, gaji_tambahan, total_gaji)

def BacaInputJam():
    masuk = float(input("Jam masuk kerja: "))
    keluar = float(input("Jam keluar kerja: "))

def BacaInputMenit():
  jam_lembur = (keluar - masuk)*60

def sapa():
  nama = input("nama: ")


def HitungLembur(jam_lembur):
    gaji_pokok = 175000
    gaji_tambahan = 0

    if jam_lembur > 8:
        jam_lebih = jam_lembur - 8
        gaji_tambahan = jam_lebih * 15000

    total_gaji = gaji_pokok + gaji_tambahan
    return gaji_pokok, gaji_tambahan, total_gaji

def TampilkanRincian(nama, jam_lembur, gaji_pokok, gaji_tambahan, total_gaji):
    print("Nama:", nama)
    print("Selamat Pagi", nama)
    print("Jam keluar kerja:", keluar)
    print("Selamat Sore", nama)
    print("-----Rincian Gaji-----")
    print("Nama:", nama)
    print(f"Waktu kerja: {jam_lembur} menit")
    print(f"Gaji pokok: Rp", gaji_pokok)
    print(f"Lembur: Rp", total_gaji)

# Memanggil fungsi utama
if __name__ == "__main__":
    main()